#! /bin/sh

bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9

bspc config border_width 2
bspc config window_gap  5
bspc config -d ^1 window_gap 0
bspc config -d ^2 window_gap 0
bspc config -d ^3 window_gap 0
bspc config -d ^4 window_gap 0
bspc config -d ^5 window_gap 0
bspc config -d ^6 window_gap 0
bspc config -d ^7 window_gap 0
bspc config -d ^8 window_gap 0
bspc config -d ^9 window_gap 0

bspc config -d ^1 border_width 2
bspc config -d ^2 border_width 2
bspc config -d ^3 border_width 2
bspc config -d ^4 border_width 2
bspc config -d ^5 border_width 2
bspc config -d ^6 border_width 2
bspc config -d ^7 border_width 2
bspc config -d ^8 border_width 2
bspc config -d ^9 border_width 2
#bspc config -m LVDS1 window_gap 0
bspc config top_padding 20 

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config normal_border_color "#303030"
bspc config focused_border_color "#AFD700"

export PANEL_FIFO="/tmp/panel-fifo"
export PATH=$PATH:~/.config/bspwm/
export XDG_CONFIG_HOME="~/marco/.config"
export BSPWM_SOCKET="/tmp/bspwm-socket"


# added 2014-06-16
bspc rule -a Gmrun floating=true center=true
bspc rule -a Gxmessage floating=true center=true
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Engrampa pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on

bspc config external_rules_command "$(which ~/.config/bspwm/Scripts/bspwm_rules.sh)"

panel dzen2 &
