#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
printf "%s\n" "The panel is already running." >&2
exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

. panel_colors

case "$flavor" in
bar)
FONT_FAMILY='-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1'
cat "$PANEL_FIFO" | panel_bar | bar -g x$PANEL_HEIGHT -f "$FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &
;;
dzen2)

# Launch left panel
       cat "$PANEL_FIFO" |  panel_dzen2 | dzen2 -h '20' -w '500' -x "0" \
            -dock -ta 'l' -e 'button2=;' -title-name 'bspwm_panel' \
            -fn "dejavu sans:size=8:antialias=true" -fg "#d0d0d0" -bg "#303030" &

# Launch middle panel
        conky -c /home/marco/.config/bspwm/bspwm_dzen_middle_conkyrc | dzen2 -h '20' -w '620' -x "500" \
            -dock -ta 'l' -e 'button2=;' -title-name 'bspwm_panel' \
            -fn "dejavu sans:size=8:antialias=true" -fg "#d0d0d0" -bg "#303030" &

# Launch right panel
        conky -c /home/marco/.config/bspwm/bspwm_dzen_conkyrc | dzen2 -h '20' -w '246' -x "1120" \
            -dock -ta 'r' -e 'button2=;' -title-name 'bspwm_panel' \
            -fn "dejavu sans:size=8:antialias=true" -fg "#d0d0d0" -bg "#303030" &
        ;;
esac

wait
