#! /bin/sh

bspc config top_padding 20 

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true

bspc config normal_border_color "#303030"
bspc config focused_border_color "#787878"

bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9

export PANEL_FIFO="/tmp/panel-fifo"
export PATH=$PATH:/home/marco/.config/bspwm/
export XDG_CONFIG_HOME="/home/marco/.config"
export BSPWM_SOCKET="/tmp/bspwm-socket"

if [ -e "$BSPWM_TREE" ] ; then
bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

bspc rule -a Gmrun floating=true center=true focus=true
bspc rule -a Gxmessage floating=true center=true
bspc rule -a File-roller floating=true
bspc rule -a Engrampa floating=true

bspc config external_rules_command "$(which ~/.config/bspwm/Scripts/bspwm_rules.sh)"

panel dzen2 &
